def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('key_hash', sa.String(length=128), nullable=False, server_default='default_hash'))
    # Ensure the new column has a default value for existing rows
    op.execute("UPDATE api_key SET key_hash = 'default_hash' WHERE key_hash IS NULL")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'key_hash')
    # ### end Alembic commands ###
