"""Add created_at and updated_at columns to Users table

Revision ID: 2d81a7cb506f
Revises: 02d0f2613704
Create Date: 2024-09-26 06:09:52.704033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2d81a7cb506f'
down_revision = '02d0f2613704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVE this line as the table doesn't exist yet:
    # op.drop_table('flask_dance_oauth')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               nullable=False)

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_key_key_hash'), ['key_hash'], unique=True)
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_index(batch_op.f('ix_api_key_key_hash'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('key_hash')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ADD the line to drop the table in the downgrade() function:
    op.drop_table('flask_dance_oauth')
    # ### end Alembic commands ###